### ISSUE TITLE
question about external wiki page

### ISSUE THREAD

**Issue by naramoksu** [nutso/redmine-plugin-wiki-external#2]
Hi,

I installed external wiki plugin and trying to use it. With wiki of redmine, it was possible to link a page of wiki page in the peoject.

Now i found all of internal wiki link connected to same external wiki page of name project identifier.

Would you kindly recommend me how to link a internal wiki link to a same page of external wiki?

I set 'Wiki Prefix' my external wiki url http://manual.domainname/, and Wiki Suffix Custom Field Name is blank.

Thanks in advance.

**Comment by nutso** [comment]
Hi,

Thanks for the question. Filling in only the wiki prefix sends all projects from Redmine to the same wiki page (as you have discovered).

You can configure the wiki page name per project. See the section on "Wiki Suffix Custom Field Name" at https://github.com/nutso/redmine-plugin-wiki-external#global-settings

Once the optional suffix field name has been set, then by default the Redmine project identifier will be used as the wiki page name. Project admins can also configure this per-project. See https://github.com/nutso/redmine-plugin-wiki-external#project-settings

**Comment by naramoksu** [comment]
Hi, Thanks for your answer. 

I have 1 more question. 
Current redmine wiki url is /project id/wiki id/page name. Is it possible to connect redmine wiki to "external wiki/page name" without project?

**Comment by nutso** [comment]
I'm not sure I understand the question completely - but I believe that would be done through the wiki prefix. 

If you're asking about changing the Redmine-internal wiki link, then that is not currently supported; the external wiki works by redirecting the existing Redmine wiki links to the external wiki.
